### ISSUE TITLE
running queries with infura and got errors

### ISSUE THREAD

**Issue by bernardpeh** [xiaoyao1991/presto-ethereum#33]
presto:default> select erc20_token,sum(erc20_value) from erc20 where erc20_blocknumber >= 4147340 and erc20_blocknumber < 4147350 group by erc20_token;
Query 20180309_035743_00011_vd6da failed: null

2018-03-09T14:57:43.526+1100	INFO	query-scheduler-6	stderr	Exception in thread "query-scheduler-6" 
2018-03-09T14:57:43.526+1100	INFO	query-scheduler-6	stderr	java.lang.AbstractMethodError
2018-03-09T14:57:43.526+1100	INFO	query-scheduler-6	stderr		at com.facebook.presto.split.SplitManager.getSplits(SplitManager.java:64)
2018-03-09T14:57:43.526+1100	INFO	query-scheduler-6	stderr		at com.facebook.presto.sql.planner.DistributedExecutionPlanner$Visitor.visitTableScan(DistributedExecutionPlanner.java:146)
2018-03-09T14:57:43.526+1100	INFO	query-scheduler-6	stderr		at com.facebook.presto.sql.planner.DistributedExecutionPlanner$Visitor.visitTableScan(DistributedExecutionPlanner.java:122)
2018-03-09T14:57:43.526+1100	INFO	query-scheduler-6	stderr		at com.facebook.presto.sql.planner.plan.TableScanNode.accept(TableScanNode.java:136)
2018-03-09T14:57:43.526+1100	INFO	query-scheduler-6	stderr		at com.facebook.presto.sql.planner.DistributedExecutionPlanner$Visitor.visitFilter(DistributedExecutionPlanner.java:201)
2018-03-09T14:57:43.526+1100	INFO	query-scheduler-6	stderr		at com.facebook.presto.sql.planner.DistributedExecutionPlanner$Visitor.visitFilter(DistributedExecutionPlanner.java:122)
2018-03-09T14:57:43.526+1100	INFO	query-scheduler-6	stderr		at com.facebook.presto.sql.planner.plan.FilterNode.accept(FilterNode.java:72)
2018-03-09T14:57:43.526+1100	INFO	query-scheduler-6	stderr		at com.facebook.presto.sql.planner.DistributedExecutionPlanner$Visitor.visitProject(DistributedExecutionPlanner.java:265)
2018-03-09T14:57:43.526+1100	INFO	query-scheduler-6	stderr		at com.facebook.presto.sql.planner.DistributedExecutionPlanner$Visitor.visitProject(DistributedExecutionPlanner.java:122)
2018-03-09T14:57:43.526+1100	INFO	query-scheduler-6	stderr		at com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:92)
2018-03-09T14:57:43.526+1100	INFO	query-scheduler-6	stderr		at com.facebook.presto.sql.planner.DistributedExecutionPlanner$Visitor.visitAggregation(DistributedExecutionPlanner.java:229)
2018-03-09T14:57:43.526+1100	INFO	query-scheduler-6	stderr		at com.facebook.presto.sql.planner.DistributedExecutionPlanner$Visitor.visitAggregation(DistributedExecutionPlanner.java:122)
2018-03-09T14:57:43.526+1100	INFO	query-scheduler-6	stderr		at com.facebook.presto.sql.planner.plan.AggregationNode.accept(AggregationNode.java:182)
2018-03-09T14:57:43.526+1100	INFO	query-scheduler-6	stderr		at com.facebook.presto.sql.planner.DistributedExecutionPlanner.doPlan(DistributedExecutionPlanner.java:108)
2018-03-09T14:57:43.526+1100	INFO	query-scheduler-6	stderr		at com.facebook.presto.sql.planner.DistributedExecutionPlanner.doPlan(DistributedExecutionPlanner.java:113)
2018-03-09T14:57:43.526+1100	INFO	query-scheduler-6	stderr		at com.facebook.presto.sql.planner.DistributedExecutionPlanner.doPlan(DistributedExecutionPlanner.java:113)
2018-03-09T14:57:43.526+1100	INFO	query-scheduler-6	stderr		at com.facebook.presto.sql.planner.DistributedExecutionPlanner.plan(DistributedExecutionPlanner.java:85)
2018-03-09T14:57:43.526+1100	INFO	query-scheduler-6	stderr		at com.facebook.presto.execution.SqlQueryExecution.planDistribution(SqlQueryExecution.java:409)
2018-03-09T14:57:43.527+1100	INFO	query-scheduler-6	stderr		at com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:280)
2018-03-09T14:57:43.527+1100	INFO	query-scheduler-6	stderr		at com.facebook.presto.execution.QueuedExecution.lambda$start$1(QueuedExecution.java:62)
2018-03-09T14:57:43.527+1100	INFO	query-scheduler-6	stderr		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
2018-03-09T14:57:43.527+1100	INFO	query-scheduler-6	stderr		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
2018-03-09T14:57:43.527+1100	INFO	query-scheduler-6	stderr		at java.lang.Thread.run(Thread.java:745)
2018-03-09T14:57:43.723+1100	INFO	query-execution-5	com.facebook.presto.event.query.QueryMonitor	TIMELINE: Query 20180309_035743_00011_vd6da :: Transaction:[d633dc7b-cf76-4046-a7b3-d9cb1ba08d21] :: elapsed 50ms :: planning 50ms :: scheduling 0ms :: running 0ms :: finishing 0ms :: begin 2018-03-09T14:57:43.475+11:00 :: end 2018-03-09T14:57:43.525+11:00

and ideas?

**Comment by xiaoyao1991** [comment]
It looks like you have a erroneous installation or setup. Can you double check if you have done as step 4 and 5 in the readme? The query works fine on my setting(note I was running my queries against Infura remote endpoint)

```
presto:default> select erc20_token,sum(erc20_value) from erc20 where erc20_blocknumber >= 4147340 and erc20_blocknumber < 4147350 group by erc20_token;
                    erc20_token                    |         _col1
---------------------------------------------------+-----------------------
 OmiseGo                                           |     5.716710350704E22
 ERC20(0x386467f1f3ddbe832448650418311a479eecfc57) |              150000.0
 ERC20(0xf0f8b0b8dbb1124261fc8d778e2287e3fd2cf4f5) |               20000.0
 StatusNetwork                                     |  2.356435422693079E23
 ERC20(0xa645264c5603e96c3b0b078cdab68733794b0a71) |      1.19811031997E11
 WINGS                                             |             2.5049E20
 Bancor                                            | 2.0630999605244042E21
 Bitquence                                         |           9.993664E11
 ICONOMI                                           |        2.184870092E19
 AdToken                                           |                2.0E13
 EOS                                               |  5.306418459819539E22
 ERC20(0x4470bb87d77b963a013db939be332f927f2b992e) |               2.169E9
 ERC20(0x177d39ac676ed1c67a2b268ad7f1e58826e5b0af) | 1.4735299999999999E23
 district0x                                        |         1.11378114E23
 Golem                                             |            1.74989E21
 ERC20(0x93e682107d1e9defb0b5ee701c71707a4b2e46bc) |          2.1851626E11
 ERC20(0xfca47962d45adfdfd1ab2d972315db4ce7ccf094) |       5.9775409835E11
 ERC20(0xe3818504c1b32bf1557b16c238b2e01fd3149c17) |   2.55014666965386E22
 Lunyr                                             |                4.9E19
 TenXPay                                           |     1.166226897899E22
 Monaco                                            |     1.308873836454E12
 ERC20(0x3d1ba9be9f66b8ee101911bc36d3fb562eac2244) |                8.4E21
 SAN                                               |         1.22337932E22
 Guppy                                             |             4732000.0
 Storj                                             |     4.149020747525E12
 DGD                                               |              4.6094E9
 REP                                               |       5.2209529481E20
 ERC20(0xd76b5c2a23ef78368d8e34288b5b65d616b746ae) |                2.9E19
 BAT                                               |         3.33026641E22
 ERC20(0x983f6d60db79ea8ca4eb9968c6aff8cfa04b3c63) |             1.4998E23
 ERC20(0x7654915a1b82d6d2d0afc37c52af556ea8983c7e) |               2.68E23
 ERC20(0x8ae4bf2c33a8e667de34b54938b0ccd03eb8cc06) |        1.225886803E12
 Humaniq                                           |     2.092184613573E12
 SNGLS                                             |                5906.0
 ERC20(0x701c244b988a513c945973defa05de933b23fe1d) |        3.571038996E20
 ERC20(0xcb97e65f07da24d46bcdd078ebebd7c6e6e3d750) |             4.00293E9
 Civic                                             |    1.2060194174158E13
 ERC20(0x43c04183a07025c13f6d4727f9626aa9c7bfafd3) |                 1.0E8
 ERC20(0x025abad9e518516fdaafbdcdb9701b37fb7ef0fa) |                   4.0
 FunFair                                           |     7.991967699908E12
 Xaurum                                            |              2.504E10
 ERC20(0x006bea43baa3f7a6f765f14f10a1a1b08334ef45) |      4.09178495202E21
 ERC20(0xa33e729bf4fdeb868b534e1f20523463d9c46bee) |                6.0E10
 QTUM                                              |      1.72792410528E21
 ERC20(0x12fef5e57bf45873cd9b62e9dbd7bfb99e32d73e) | 4.4080000000000004E22
 ERC20(0xd4fa1460f537bb9085d22c7bccb5dd450ef28e3a) |            3.61683E10
 ERC20(0xe2f45f1660dc99daf3bd06f637ab1e4debc15bde) |               5.64E10
 ERC20(0x8f3470a7388c05ee4e7af3d01d8c722b0ff52374) |             1.2201E19
 Gnosis                                            |                9.0E18
(49 rows)
```

**Comment by bernardpeh** [comment]
thanks for the comment @xiaoyao1991. I've followed exactly the same steps outlined in README. just wondering my os or config has anything got to do with it. would be nice if we could dockerise the setup. mind sharing your working config?

I'm using mac sierra 10.12.6, 4G ram, java version "1.8.0_162"

config.properties
```
coordinator=true
node-scheduler.include-coordinator=true
http-server.http.port=8080
query.max-memory=5GB
query.max-memory-per-node=1GB
discovery-server.enabled=true
discovery.uri=http://localhost:8080
```

jvm.config
```
-server
-Xmx16G
-XX:+UseG1GC
-XX:G1HeapRegionSize=32M
-XX:+UseGCOverheadLimit
-XX:+ExplicitGCInvokesConcurrent
-XX:+HeapDumpOnOutOfMemoryError
-XX:+ExitOnOutOfMemoryError
```

node.properties
```
node.environment=production
node.id=iiifffff-ffff-ffff-ffff-ffffffffffff
node.data-dir=/Users/myuser/presto-server-0.196/data
```

**Comment by bernardpeh** [comment]
issue fixed.
