### ISSUE TITLE
Any query involving the field block_uncles or  block_transactions fails

### ISSUE THREAD

**Issue by BenKnigge** [xiaoyao1991/presto-ethereum#43]
I'm guessing that this my have to do with array types since both fields are of type array(varchar(66))

SQL 

select block_transactions, block_uncles from ethereum.default.block limit 1;

Error Type | INTERNAL_ERROR
-- | --
Error Code | GENERIC_INTERNAL_ERROR (65536)
Stack Trace | java.lang.NoSuchMethodError: com.facebook.presto.spi.block.BlockBuilderStatus: method <init>()V not found 	at im.xiaoyao.presto.ethereum.EthereumRecordCursor.serializeList(EthereumRecordCursor.java:301) 	at im.xiaoyao.presto.ethereum.EthereumRecordCursor.serializeObject(EthereumRecordCursor.java:277) 	at im.xiaoyao.presto.ethereum.EthereumRecordCursor.getObject(EthereumRecordCursor.java:219) 	at com.facebook.presto.spi.RecordPageSource.getNextPage(RecordPageSource.java:121) 	at com.facebook.presto.operator.TableScanOperator.getOutput(TableScanOperator.java:242) 	at com.facebook.presto.operator.Driver.processInternal(Driver.java:373) 	at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:282) 	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:672) 	at com.facebook.presto.operator.Driver.processFor(Driver.java:276) 	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:973) 	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162) 	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:477) 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) 	at java.lang.Thread.run(Thread.java:748)

**Comment by lispmind** [comment]
same error for me ,  anyone can give some tips?

select block_transactions, block_uncles from ethereum.default.block limit 1;

Query 20181108_043315_00033_iecrh, FAILED, 1 node
Splits: 116 total, 11 done (9.48%)
0:00 [0 rows, 0B] [0 rows/s, 0B/s]

Query 20181108_043315_00033_iecrh failed: com.facebook.presto.spi.block.BlockBuilderStatus: method <init>()V not found
