### ISSUE TITLE
 Failed connecting to Hive metastore: [192.0.2.3:9083]

### ISSUE THREAD

**Issue by luolixuan** [xiaoyao1991/presto-ethereum#47]
Hi, I have encountered this problem for a long time.

I followed the instructions to install presto, presto-cli. For presto, I used discovery.uri=http://127.0.0.1:8080, and in hive.properties I use hive.metastore.uri=thrift://127.0.0.1:9083.

Following the instructions,
1. run Geth:  geth --syncmode "full" --gcmode "archive"
2. run presto: sudo bin/launcher start
Already running as 821
3. run presto-cli: ./presto --server localhost:8080 --catalog hive --schema default

But when I want to do the query, it raises the problem:
<img width="845" alt="image" src="https://user-images.githubusercontent.com/29030991/58118019-fa569080-7bcd-11e9-84d6-240fad3e0d9d.png">

And when I try to run the example query, it shows: 
<img width="845" alt="image" src="https://user-images.githubusercontent.com/29030991/58118052-0e01f700-7bce-11e9-94b3-02b9b84fd3bb.png">

I am not sure what is going on wrong. Seeking for help. Thanks in advance

**Comment by xiaoyao1991** [comment]
why are you trying to connect to hive?

**Comment by luolixuan** [comment]
@xiaoyao1991 First,  I used jmx as" create etc/catalog/jmx.properties with the following contents to mount the jmx connector as the jmx catalog". However it shows up:
<img width="875" alt="image" src="https://user-images.githubusercontent.com/29030991/58124488-59230680-7bdc-11e9-9040-6385e90f3579.png">

So I just installed hive and tried. What's wrong with my settings? How I do the example query as shown in the instructions?

**Comment by xiaoyao1991** [comment]
Did you try setting up according to the README without the jmx? The setup instructions are pretty clear in the README, and if you setup correctly, all you need to do is `presto-cli --server localhost:8080 --catalog ethereum --schema default`

**Comment by luolixuan** [comment]
@xiaoyao1991 Yes. I followed all the instructions. But when I run it, it shows:
<img width="650" alt="image" src="https://user-images.githubusercontent.com/29030991/58128589-03535c00-7be6-11e9-99c1-80d079d1051e.png">
There is no presto-cli, so I use "./presto --server localhost:8080 --catalog hive --schema default" instead. But it still does not work. 

Is there a presto-cli package or command? I install Presto CLI by following this link: https://prestosql.io/docs/current/installation/cli.html

**Comment by xiaoyao1991** [comment]
Right, you just need to install the cli. The name of the cli is just `presto`, not `presto-cli`, so try `presto --server localhost:8080 --catalog ethereum --schema default`

**Comment by xiaoyao1991** [comment]
make sure you have the cli in your PATH

**Comment by luolixuan** [comment]
@xiaoyao1991 Hi, I reinstall all the things following the instructions(on MacOS).
I am using Geth. These are my configurations:
<img width="747" alt="image" src="https://user-images.githubusercontent.com/29030991/58146893-27cf2880-7c26-11e9-8105-c53f7d35a453.png">
<img width="535" alt="image" src="https://user-images.githubusercontent.com/29030991/58146900-2d2c7300-7c26-11e9-905c-e433ea1797af.png">

I first start geth by: geth --rpc --rpcaddr "127.0.0.1" --rpcport "8545"
Then I start the server by: sudo bin/launcher start
when I refresh http://localhost:8080, it shows following, then "cannot connect to server": 
<img width="1234" alt="image" src="https://user-images.githubusercontent.com/29030991/58147029-b2178c80-7c26-11e9-9b08-9a4d4bdeefd8.png">

I restart the server several times: 
<img width="613" alt="image" src="https://user-images.githubusercontent.com/29030991/58147106-028eea00-7c27-11e9-8949-9ca8ce9f9f4f.png">
But it seems that I can connect to the server in several seconds, then the server just automatically stops. I am really confused by that since I have reinstalled it serval times with the instructions. Thanks in advance.

**Comment by luolixuan** [comment]
I printed out the log when starting the server and found this error: 
`2019-05-22T22:21:47.985-0400	ERROR	main	io.prestosql.server.PrestoServer	No service providers of type io.prestosql.spi.Plugin
java.lang.IllegalStateException: No service providers of type io.prestosql.spi.Plugin
	at com.google.common.base.Preconditions.checkState(Preconditions.java:588)
	at io.prestosql.server.PluginManager.loadPlugin(PluginManager.java:166)
	at io.prestosql.server.PluginManager.loadPlugin(PluginManager.java:157)
	at io.prestosql.server.PluginManager.loadPlugins(PluginManager.java:138)
	at io.prestosql.server.PrestoServer.run(PrestoServer.java:125)
	at io.prestosql.server.PrestoServer.main(PrestoServer.java:70)


2019-05-22T22:21:47.986-0400	INFO	Thread-88	io.airlift.bootstrap.LifeCycleManager	Life cycle stopping...`

**Comment by luolixuan** [comment]
I printed out the log of starting the server and found this error: 

`2019-05-22T22:21:47.985-0400	ERROR	main	io.prestosql.server.PrestoServer	No service providers of type io.prestosql.spi.Plugin
java.lang.IllegalStateException: No service providers of type io.prestosql.spi.Plugin
	at com.google.common.base.Preconditions.checkState(Preconditions.java:588)
	at io.prestosql.server.PluginManager.loadPlugin(PluginManager.java:166)
	at io.prestosql.server.PluginManager.loadPlugin(PluginManager.java:157)
	at io.prestosql.server.PluginManager.loadPlugins(PluginManager.java:138)
	at io.prestosql.server.PrestoServer.run(PrestoServer.java:125)
	at io.prestosql.server.PrestoServer.main(PrestoServer.java:70)


2019-05-22T22:21:47.986-0400	INFO	Thread-88	io.airlift.bootstrap.LifeCycleManager	Life cycle stopping...`

Looking for help.

**Comment by martint** [comment]
@xiaoyao1991, the plugin needs to be updated to the latest version of the Presto SPI. Here's a document on how to get started https://github.com/prestosql/presto/wiki/Migration. We're happy to help if you need it, too. If you have any questions, please join the Presto slack channel at https://prestosql.io/community.html.
